### ISSUE TITLE
`TableView`: decimal alignment

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#1009]
This should (apparently) be supported by setting `align="char"` and `char="."` on a `td`, but it doesn’t seem to be supported by many (or any) browsers.

One solution might be to use two table columns, one for the integral part and one for the period/mantissa. 

**Update:** No, that would break selectability. Here’s a [pure CSS/HTML solution](https://stackoverflow.com/questions/29852849/aligning-numbers-at-decimal-point-angular-ui-grid) that might be worth trying:

```html
<div>
    <span class="int">11.</span><span class="float">293</span>
</div>
<div>
    <span class="int">233424.</span><span class="float">89</span>
</div>
```

```css
.int, .float{
    display: inline-block;
    width: 100px;
}
.int{
    text-align: right;
}
.float{
    text-align: left;
}
```
