### ISSUE TITLE
MacOS GitHub runner, Firefox support

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#1037]
- [x] Add MacOS runner to GitHub `build` workflow
- [x] `test` job to install headless Firefox into Puppeteer
- [x] `shopt` glob step to only run on `ubuntu` (see below)

See also:
- #583 
- [Using a matrix strategy](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow)
- [Headless Firefox with Puppeteer](https://scrapfly.io/blog/how-to-scrape-with-headless-firefox/)
- [Puppeteer launch options](https://pptr.dev/api/puppeteer.puppeteerlaunchoptions)

***
```yml
    - name: enable-glob
      run: |
        shopt -s extglob nullglob globstar
      if: runner.os == ‘Linux’
```
