### ISSUE TITLE
`visibility:collapse` broken on Safari

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#1310]
We style hidden table rows with `visibility: collapse`, rather than `display:none`. There was a good reason for this: collapsed rows are still part of the table and their width is taken into account when computing column widths, avoiding the columns resizing as the data selection changes.

However, Safari doesn't implement this properly.

There are documented (but clearly extremely hacky) ways of targetting Safari only:

```css
@supports (hanging-punctuation: first) and (font: -apple-system-body) and (-webkit-appearance: none) {
  .safari-only {
    background-color: red;
  }
}
```

Also it's probably worth checking that we actually need still `visibility:collapse` to achieve uniform column size (for example that we don't compute it in some other way).
